-- Taula socis
CREATE TABLE IF NOT EXISTS socis (
    numero_soci INTEGER PRIMARY KEY,
    cognoms VARCHAR(100),
    nom VARCHAR(50),
    email VARCHAR(100) NULL
);

-- Insert socis
INSERT INTO socis (numero_soci, nom, cognoms, email) VALUES
(8766, 'Jose Vicente', 'Aguilella Casanova', 'joviac3@gmail.com'),
(8485, 'Pedro', 'Alvarez Valencia', NULL),
(8561, 'Miquel', 'Amador Guillem', 'miq1952@gmail.com'),
(8764, 'Manuel', 'Arbiol García', 'manius.ag@gmail.com'),
(8396, 'Juan Luis', 'Arroyo Durán', 'juanluis01@gmail.com'),
(6726, 'Mariano', 'Baraut Baraut', NULL),
(7226, 'Jorge', 'Benito Navarro', NULL),
(8542, 'Alfonso', 'Bermejo Alías', NULL),
(8077, 'Agustí', 'Boix Gonzalez', 'agustiboixgonzalez@gmail.com'),
(8583, 'Carlos', 'Bove Esparducer', 'carlosbove@gmail.com'),
(261, 'Jordi', 'Cabre Camps', 'jordicabrecamps@gmail.com'),
(8653, 'Josep', 'Campolier Montsant', 'compolierjosep@gmail.com'),
(8707, 'Jose Maria', 'Campos Gonzalez', NULL),
(8731, 'Manuel', 'Caro Ortigosa', NULL),
(2749, 'Joan', 'Carrasco Montes', 'joancarmon@hotmail.com'),
(7046, 'Alfonso', 'Carreño Serra', 'alfonsocarrenyo@gmail.com'),
(8408, 'Josep Maria', 'Casamor Regull', NULL),
(7618, 'Pere', 'Casanova Fregine', 'p.casanova.f@gmail.com'),
(7938, 'Rafael', 'Cervantes Solsona', NULL),
(8683, 'Luis', 'Chuecos Enriquez', 'luiscarlos_chuecos@hotmail.com'),
(6110, 'Jaume', 'Comas Ferrer', NULL),
(8433, 'Enric', 'Curcó Aguarod', 'ecurco@hotmail.com'),
(8574, 'Juan Antonio', 'De Gea Ros', 'joandegea@gmail.com'),
(8746, 'Alfred', 'De La Prida Gonzalez', 'alfreddlpg1965@hotmail.com'),
(3287, 'Jordi', 'De La Riva Aguado', 'jdelarivaaguado@hotmail.com'),
(8747, 'Jordi', 'Domingo Juan', 'jdomingojuan@gmail.com'),
(8264, 'Eduard', 'Díaz Martín', 'bluesmartini@hotmail.com'),
(7541, 'Pedro', 'Ferras Omella', NULL),
(407, 'Xavier', 'Fina Pasanau', 'xavifina48@gmail.com'),
(7196, 'Joan', 'Fito Ibañez', 'joanfito@gmail.com'),
(8727, 'Joaquim', 'Font i Pagès', 'font@dmf.es'),
(8693, 'Antonio', 'Fuentes Morilla', 'tomifuentes242@gmail.com'),
(8715, 'Enric', 'Garcia Baucells', 'kike@bitacora.cat'),
(8716, 'Artur', 'Garcia Satorra', 'arturpintors@gmail.com'),
(2603, 'Claudi', 'Garriga Rostey', 'claudigarriga@gmail.com'),
(8387, 'Joaquim', 'Gibernau Quintana', NULL),
(8725, 'Xavier', 'Gibert Casanovas', NULL),
(8373, 'Vicent', 'Girbes Gonzalez', 'vgirbes@yahoo.es'),
(8682, 'Mariano', 'Gonzalvo Domingo', 'srgonzalvo@hotmail.es'),
(8062, 'Joan', 'Grau Cadena', 'jgc1992c@gmail.com'),
(8648, 'Albert', 'Gómez Ametller', 'algoam@gmail.com'),
(8695, 'Jorge', 'Gómez García', NULL),
(8311, 'Ignacio', 'Hernández Falcó', 'ignaciohernandezfalco@gmail.com'),
(8215, 'Rafael', 'Herrera Nuñez', NULL),
(8115, 'Jose', 'Ibañez Forte', 'jif42@hotmail.es'),
(5818, 'Vicens', 'Inocentes Sivilla', 'vicenteinocentes@telefonica.net'),
(7308, 'Raúl', 'Jarque Sanchez', 'rauljarque2@hotmail.com'),
(8483, 'Francesc', 'Ledo Gasia', NULL),
(3019, 'Esteve', 'Leon Puig', 'eslepu@hotmail.com'),
(2543, 'Antoni', 'Llauet Amiell', NULL),
(8482, 'Miguel', 'Lopez Mallach', 'miguel.lmfotografia@gmail.com'),
(7439, 'Isidoro', 'Lopez Zurdo', NULL),
(8689, 'Joan', 'Lorca Badosa', NULL),
(8732, 'Eder', 'Luengo Torre', 'ederlt80@gmail.com'),
(8407, 'Mariano', 'Manzano García', 'mariano.manzano@yahoo.es'),
(1381, 'Salvador', 'Marin Bellido', 'salvadormarin20@yahoo.es'),
(8121, 'Josep', 'Mayor Piñol', 'maypimayor@gmail.com'),
(8556, 'Antonio', 'Medina Alventosa', 'tonima64@gmail.com'),
(8464, 'Antonio', 'Melgarejo Nicolàs', NULL),
(8431, 'Rosend', 'Mercader Bascón', 'rossend.mercader@gmail.com'),
(8366, 'Eduardo', 'Millán Sánchez', 'eduardomillansanchez@gmail.com'),
(8745, 'Francisco', 'Miralles Artigas', 'carrera9117777@gmail.com'),
(8438, 'Angel', 'Mora Santamaria', 'anjel.j.o.mora@gmail.com'),
(8436, 'Rafael', 'Moreno Barcia', 'pericolepanto@hotmail.com'),
(8137, 'Joan Maria', 'Muntané Merino', 'joanma.muntane@gmail.com'),
(8645, 'Manel', 'Murciano Diaz', 'manelmurciano6@gmail.com'),
(987, 'David', 'Nogues Blanco', 'davidnobla@gmail.com'),
(6855, 'Jesus', 'Ortiz Romero', 'jesusortizromero@telefonica.net'),
(8216, 'Jose', 'Pallisa Gonzalez', 'tekniko07@gmail.com'),
(8409, 'Héctor', 'Perez Castillejos', 'hperezcastillejos@yahoo.es'),
(8705, 'Fco. Javier', 'Perez Ribas', 'dosporsosi@gmail.com'),
(8743, 'Jordi', 'Piñol Fort', 'jpinyolfort@gmail.com'),
(8181, 'Ricardo', 'Polls Badia', 'raeltais@gmail.com'),
(3463, 'Manuel', 'Querol Viñals', 'mquerol@outlook.es'),
(8756, 'Manuel', 'Ramon Pérez', 'ramonperzmanuel73@hotmail.com'),
(8535, 'Gregorio', 'Rastrollo Mosquero', 'gregoriorastrollo1962@gmail.com'),
(8608, 'Jordi', 'Rich Ferré', 'jordirichferre@gmail.com'),
(6811, 'Juan Manuel', 'Rodriguez Airo', NULL),
(7909, 'Juan', 'Rodriguez Fernandez', 'juferrodri60@gmail.com'),
(8133, 'Juan', 'Rodriguez Lopez', NULL),
(8604, 'Joan', 'Rosell Gomà', NULL),
(8664, 'Joel Lincoln', 'Rosero Sanchez', 'joel-lincoln@hotmail.com'),
(6470, 'Leandro', 'Roy Sobrevilla', NULL),
(8741, 'Guillem', 'Ruiz Camara', 'guillermor_84@hotmail.com'),
(7297, 'Angel', 'Ruiz Martinez', NULL),
(8742, 'Ramon', 'Rull Calero', 'ramonpower2002@yahoo.es'),
(7967, 'Manuel', 'Sanchez Molera', 'manelsan@hotmail.es'),
(8575, 'Josep Maria', 'Sans Lladó', NULL),
(7602, 'Juan Felix', 'Santos Gonzalez', NULL),
(8296, 'Jose Antonio', 'Saucedo Bascón', 'saucedobascon@hotmail.com'),
(8309, 'Fernando', 'Segura Gonzalez', 'loobvio.fer@gmail.com'),
(6203, 'Josep', 'Selga  Sarro', NULL),
(8524, 'Rafael', 'Soto Castillo', 'rsoto@tmb.cat'),
(8728, 'Jesús', 'Sánchez Villa', 'jesanchovi@gmail.com'),
(7528, 'Tomas', 'Trens Ojea', 'tomimcmli@gmail.com'),
(8208, 'Antonio', 'Trillo Palma', 'antriyo@hotmail.com'),
(6512, 'Josep', 'Valles Ros', 'pitujv@gmail.com'),
(8649, 'Jose Manuel', 'Veiga Losada', 'jmvlbcn@gmail.com'),
(8212, 'Francesc', 'Verdugo Martín', NULL),
(8523, 'Juan', 'Veza Molla', 'juanv000@gmail.com'),
(8603, 'Josep', 'Veza Mollá', NULL),
(7586, 'Josep Maria', 'Viaplana Lleonart', 'josepmaria.viaplana@gmail.com'),
(8690, 'Josep', 'Vila Clopes', 'pepvila1966@gmail.com'),
(3780, 'Eduard', 'Yepes Martinez', 'skakimat@hotmail.com');
