name: Supabase – Deploy to Prod (on main)

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/DISABLED/**'

jobs:
  apply-migrations-prod:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Supabase CLI
        run: |
          npm install supabase --save-dev
          npx supabase --version

      - name: Link to PROD project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          npx supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF_PROD }}

      - name: Apply migrations to PROD
        run: |
          npx supabase db push
