name: Supabase – Deploy to Prod (on main)

# Required secrets (configure in GitHub > Settings > Secrets and variables > Actions):
# - SUPABASE_ACCESS_TOKEN: Your Supabase access token with project permissions
# - SUPABASE_PROJECT_REF_PROD: Your production project reference ID

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_PROJECT_REF_PROD: ${{ secrets.SUPABASE_PROJECT_REF_PROD }}

jobs:
  apply-migrations-prod:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Supabase CLI
        run: |
          npm install supabase --save-dev
          npx supabase --version

      - name: Validate environment
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "❌ SUPABASE_ACCESS_TOKEN secret is not set"
            echo "Please configure it in GitHub Settings > Secrets and variables > Actions"
            exit 1
          fi
          if [ -z "$SUPABASE_PROJECT_REF_PROD" ]; then
            echo "❌ SUPABASE_PROJECT_REF_PROD secret is not set"
            echo "Please configure it in GitHub Settings > Secrets and variables > Actions"
            exit 1
          fi
          echo "✅ All required secrets are configured"

      - name: Link to PROD project
        run: |
          echo "Linking to project ref: ${SUPABASE_PROJECT_REF_PROD}"
          npx supabase link --project-ref ${SUPABASE_PROJECT_REF_PROD}

      - name: Apply migrations to PROD
        run: |
          echo "Applying migrations to production..."
          npx supabase db push
