name: Supabase – Validate PR (apply to Staging)

on:
  pull_request:
    paths:
      - 'supabase/migrations/DISABLED/**'

jobs:
  apply-migrations-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Supabase CLI
        run: |
          npm install supabase --save-dev
          npx supabase --version

      - name: Link to STAGING project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          npx supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF_STAGING }}

      - name: Apply migrations to STAGING
        run: |
          npx supabase db push
