name: Supabase – Validate PR (apply to Staging)name: Supabase – Validate PR (apply to Staging)



on:on:

  pull_request:  pull_request:

    paths:    paths:

      - 'supabase/migrations/**'      - 'supabase/migrations/**'



jobs:jobs:

  apply-migrations-staging:  apply-migrations-staging:

    runs-on: ubuntu-latest    runs-on: ubuntu-latest

    permissions:    permissions:

      contents: read      contents: read

    steps:    steps:

      - name: Checkout      - name: Checkout

        uses: actions/checkout@v4        uses: actions/checkout@v4



      - name: Setup Node      - name: Setup Node

        uses: actions/setup-node@v4        uses: actions/setup-node@v4

        with:        with:

          node-version: 20          node-version: 20



      - name: Install Supabase CLI      - name: Install Supabase CLI

        run: |        run: |

          npm install supabase --save-dev          npm install supabase --save-dev

          npx supabase --version          npx supabase --version



      - name: Link to STAGING project      - name: Link to STAGING project

        env:        env:

          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

        run: |        run: |

          npx supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF_STAGING }}          npx supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF_STAGING }}



      - name: Apply migrations to STAGING      - name: Apply migrations to STAGING

        run: |        run: |

          npx supabase db push          npx supabase db push
