name: Supabase – Validate PR (apply to Staging)

# This workflow validates pull requests by applying migrations to staging.
#
# SETUP REQUIRED:
# 1. Go to GitHub Repository Settings > Secrets and variables > Actions
# 2. Add this repository secret:
#    - SUPABASE_ACCESS_TOKEN: Your Supabase access token (get from https://supabase.com/dashboard/account/tokens)
#
# The project reference is automatically read from the environment.
# Once secrets are configured, this workflow will run automatically.

on:
  pull_request:
    paths:
      - 'supabase/migrations/**'

jobs:
  validate-on-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Supabase CLI
        run: |
          npm install supabase --save-dev
          npx supabase --version

      - name: Validate secrets configuration
        id: check-secrets
        run: |
          echo "Checking repository secrets configuration..."

          # Check if SUPABASE_ACCESS_TOKEN is properly set
          if [ "${{ secrets.SUPABASE_ACCESS_TOKEN }}" = "" ]; then
            echo "::error::SUPABASE_ACCESS_TOKEN secret is not configured"
            echo "Go to Repository Settings > Secrets and variables > Actions"
            echo "Add SUPABASE_ACCESS_TOKEN with your Supabase access token"
            echo "Get your token from: https://supabase.com/dashboard/account/tokens"
            exit 1
          fi

          echo "✅ All secrets are properly configured"
          echo "secrets-ok=true" >> $GITHUB_OUTPUT

      - name: Link to staging project
        if: steps.check-secrets.outputs.secrets-ok == 'true'
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "Linking to staging project..."
          # Use the project reference from the codebase
          PROJECT_REF="qbldqtaqawnahuzlzsjs"
          echo "Using project reference: $PROJECT_REF"
          npx supabase link --project-ref "$PROJECT_REF"

      - name: Apply migrations to staging
        if: steps.check-secrets.outputs.secrets-ok == 'true'
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "Applying database migrations to staging..."
          npx supabase db push
